### ISSUE TITLE
启动不起来！

### ISSUE THREAD

**Issue by yellowfrogCN** [liang869219658/Music#1]
我的系统是windows的，install后启动不了！

$ npm start

> webpack-dev-boilerplate@2.0.0 start C:\Users\Administrator\Desktop\Music
> cross-env NODE_ENV=development node conf/server.dev.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\Desktop\Music\public\react-manifest.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Music\conf\webpack.dev.config.js:67:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Music\conf\server.dev.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! webpack-dev-boilerplate@2.0.0 start: `cross-env NODE_ENV=development node conf/server.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-dev-boilerplate@2.0.0 start script 'cross-env NODE_ENV=development node conf/server.dev.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-dev-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node conf/server.dev.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-dev-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-dev-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\Desktop\Music\npm-debug.log

**Comment by liang869219658** [comment]
//首先运行dll预打包

$ npm run start:pre


//打包完成，启动项目

$ npm start

**Comment by yellowfrogCN** [comment]
哦哦!谢谢，按你方法做了，但还是错误~~~~~弹出页面显示 Cannot GET / 

ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "import" specified in "C:\\Users\\Administrator\\Deskt
op\\Music\\.babelrc" at 2, attempted to resolve relative to "C:\\Users\\Administrator\\Desktop\\Music"
    at C:\Users\Administrator\Desktop\Music\node_modules\.6.24.0@babel-core\lib\transformation\file\option
s\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\Administrator\Desktop\Music\node_modules\.6.24.0@babel-core\lib
\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\Administrator\Desktop\Music\node_modules\.6.24.0@babel-core\li
b\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\Administrator\Desktop\Music\node_modules\.6.24.0@babel-core\lib\transf
ormation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\Administrator\Desktop\Music\node_modules\.6.24.0@babel-core\lib\transfor
mation\file\index.js:212:65)
    at new File (C:\Users\Administrator\Desktop\Music\node_modules\.6.24.0@babel-core\lib\transformation\f
ile\index.js:135:24)
    at Pipeline.transform (C:\Users\Administrator\Desktop\Music\node_modules\.6.24.0@babel-core\lib\transf
ormation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\Desktop\Music\node_modules\.6.4.1@babel-loader\lib\index.js:46:20
)
    at C:\Users\Administrator\Desktop\Music\node_modules\.6.4.1@babel-loader\lib\fs-cache.js:79:18
    at ReadFileContext.callback (C:\Users\Administrator\Desktop\Music\node_modules\.6.4.1@babel-loader\lib
\fs-cache.js:15:14)

**Comment by liang869219658** [comment]
。。。重新拉一下
git pull
